version: "3.8"

services:
  portfolio-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - SMTP_MAIL_ID=${SMTP_MAIL_ID}
      - SMTP_MAIL_PASSWORD=${SMTP_MAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:5000/', timeout=10)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: portfolio-network
